const PROFILE_DELETION_ROUTES = {
  MAIN: "PROFILE_DELETION_ROUTES_MAIN",
  START: "PROFILE_DELETION_ROUTES_START",
  CONFIRM: "PROFILE_DELETION_ROUTES_CONFIRM",
  SUCCESS: "PROFILE_DELETION_ROUTES_SUCCESS"
};

export default PROFILE_DELETION_ROUTES;
